Add-Type -AssemblyName System.Drawing
Add-Type -AssemblyName System.Drawing.Common -ErrorAction SilentlyContinue
$W=1284; $H=2778
$out='C:\Users\joseph marvin\Downloads'
$bg=[System.Drawing.Color]::FromArgb(248,246,239); $green=[System.Drawing.Color]::FromArgb(18,101,78); $dark=[System.Drawing.Color]::FromArgb(20,39,34); $gold=[System.Drawing.Color]::FromArgb(194,145,47); $muted=[System.Drawing.Color]::FromArgb(100,114,107); $white=[System.Drawing.Color]::White
$fontSerif='Georgia'; $fontSans='Arial'
function F($name,$size,$style=0){ New-Object System.Drawing.Font($name,$size,[System.Drawing.FontStyle]$style) }
function CenterText($g,$text,$font,$brush,$y){$size=$g.MeasureString($text,$font);$g.DrawString($text,$font,$brush,(($W-$size.Width)/2),$y)}
function RoundRect($g,$brush,$x,$y,$w,$h,$r){$path=New-Object System.Drawing.Drawing2D.GraphicsPath;$path.AddArc($x,$y,$r,$r,180,90);$path.AddArc($x+$w-$r,$y,$r,$r,270,90);$path.AddArc($x+$w-$r,$y+$h-$r,$r,$r,0,90);$path.AddArc($x,$y+$h-$r,$r,$r,90,90);$path.CloseFigure();$g.FillPath($brush,$path)}
function NewCanvas(){ $b=New-Object System.Drawing.Bitmap($W,$H);$g=[System.Drawing.Graphics]::FromImage($b);$g.SmoothingMode='AntiAlias';$g.Clear($bg); return @($b,$g) }
function Header($g){$g.DrawString('9:41',(F $fontSans 30 1),[System.Drawing.Brushes]::Black,50,30); $g.DrawString('Legal ',$(F $fontSans 42 1),[System.Drawing.Brushes]::Black,150,115);$g.DrawString('Advisor',(F $fontSans 42 1),[System.Drawing.Brush]::new($gold),325,115); RoundRect $g ([System.Drawing.Brush]::new($white) ) 52 108 80 80 20; $g.DrawString('?',$(F $fontSans 36),[System.Drawing.Brush]::new($dark),70,125); RoundRect $g ([System.Drawing.Brush]::new($white)) 1075 108 75 80 20; $g.DrawString('?',$(F $fontSans 32),[System.Drawing.Brush]::new($dark),1095,128); RoundRect $g ([System.Drawing.Brush]::new($green)) 1160 108 105 80 20; $g.DrawString('Sign in',$(F $fontSans 25 1),[System.Drawing.Brushes]::White,1175,134);$g.DrawLine([System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(225,222,213),2),0,220,$W,220)}
# home
$a=NewCanvas();$b=$a[0];$g=$a[1];Header $g;CenterText $g 'LEGAL GUIDANCE, MADE HUMAN' (F $fontSans 25 1) ([System.Drawing.Brush]::new($green)) 420;CenterText $g 'Legal help starts' (F $fontSerif 72 1) ([System.Drawing.Brush]::new($dark)) 540;CenterText $g 'with' (F $fontSerif 72 1) ([System.Drawing.Brush]::new($dark)) 635;CenterText $g 'understanding.' (F $fontSerif 78 2) ([System.Drawing.Brush]::new($green)) 730;CenterText $g "Tell the Legal Advisor what's" (F $fontSans 34) ([System.Drawing.Brush]::new($muted)) 930;CenterText $g 'happening. Understand the law,' (F $fontSans 34) ([System.Drawing.Brush]::new($muted)) 985;CenterText $g 'explore your options, and connect' (F $fontSans 34) ([System.Drawing.Brush]::new($muted)) 1040;CenterText $g 'with the right lawyer when you need one.' (F $fontSans 34) ([System.Drawing.Brush]::new($muted)) 1095;RoundRect $g ([System.Drawing.Brush]::new($white)) 80 1270 1124 420 40;$g.DrawString("Tell me what's happening in your",(F $fontSans 30),[System.Drawing.Brush]::new($muted),140,1360);$g.DrawString('own words...', (F $fontSans 30),[System.Drawing.Brush]::new($muted),140,1415);$g.DrawLine([System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(225,222,213),2),130,1515,1135,1515);$g.DrawString('Uganda · Private & secure',(F $fontSans 26),[System.Drawing.Brush]::new($muted),140,1570);RoundRect $g ([System.Drawing.Brush]::new($green)) 700 1540 450 115 22;$g.DrawString('Ask a legal question',(F $fontSans 27 1),[System.Drawing.Brushes]::White,755,1575);CenterText $g 'Or start here:' (F $fontSans 25) ([System.Drawing.Brush]::new($muted)) 1800;foreach($t in @('Work problem','Housing','Contract')){RoundRect $g ([System.Drawing.Brush]::new($white)) (if($t -eq 'Work problem'){210}elseif($t -eq 'Housing'){600}else{430}) (if($t -eq 'Contract'){1960}else{1810}) (if($t -eq 'Contract'){260}else{285}) 78 36;$g.DrawString($t,(F $fontSans 25),[System.Drawing.Brush]::new($green),(if($t -eq 'Work problem'){245}elseif($t -eq 'Housing'){650}else{490}),(if($t -eq 'Contract'){1985}else{1835}))};$b.Save("$out\LegalAdvisor-iPhone-home-1284x2778.png",[System.Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$b.Dispose()
# chat
$a=NewCanvas();$b=$a[0];$g=$a[1];Header $g;$g.DrawString('Legal Assistant',(F $fontSerif 58 1),[System.Drawing.Brush]::new($dark),80,330);$g.DrawString('Uganda · Online',(F $fontSans 25),[System.Drawing.Brush]::new($green),82,420);RoundRect $g ([System.Drawing.Brush]::new($green)) 360 590 820 175 32;$g.DrawString('My landlord locked me out.',(F $fontSans 31),[System.Drawing.Brushes]::White,410,640);RoundRect $g ([System.Drawing.Brush]::new($white)) 80 860 1070 550 35;$g.DrawString('I’m sorry you’re dealing with this.',(F $fontSans 31 1),[System.Drawing.Brush]::new($dark),130,930);$g.DrawString('Let’s clarify what happened so I can', (F $fontSans 30),[System.Drawing.Brush]::new($dark),130,1000);$g.DrawString('explain your options under Ugandan law.',(F $fontSans 30),[System.Drawing.Brush]::new($dark),130,1055);$g.DrawString('Did you receive a written notice?',(F $fontSans 30),[System.Drawing.Brush]::new($dark),130,1140);$g.DrawString('Your information is private and secure.',(F $fontSans 25),[System.Drawing.Brush]::new($muted),130,1260);RoundRect $g ([System.Drawing.Brush]::new($white)) 80 2240 1124 170 30;$g.DrawString('Type your legal question...',(F $fontSans 29),[System.Drawing.Brush]::new($muted),125,2300);RoundRect $g ([System.Drawing.Brush]::new($green)) 1035 2265 120 110 25;$g.DrawString('?',(F $fontSans 42 1),[System.Drawing.Brushes]::White,1070,2293);$b.Save("$out\LegalAdvisor-iPhone-assistant-1284x2778.png",[System.Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$b.Dispose()
# lawyers
$a=NewCanvas();$b=$a[0];$g=$a[1];Header $g;$g.DrawString('Find the right lawyer',(F $fontSerif 58 1),[System.Drawing.Brush]::new($dark),80,340);$g.DrawString('Verified advocates available in Uganda',(F $fontSans 27),[System.Drawing.Brush]::new($muted),82,435);RoundRect $g ([System.Drawing.Brush]::new($white)) 80 550 1124 115 28;$g.DrawString('?  Search by legal issue or location',(F $fontSans 28),[System.Drawing.Brush]::new($muted),125,590);$names=@('Amina K. · Kampala','David M. · Entebbe','Sarah N. · Jinja');$special=@('Family & property law','Employment & contracts','Civil litigation');for($i=0;$i -lt 3;$i++){ $y=800+$i*430;RoundRect $g ([System.Drawing.Brush]::new($white)) 80 $y 1124 350 32;RoundRect $g ([System.Drawing.Brush]::new($green)) 135 ($y+70) 120 120 60;$g.DrawString($names[$i].Substring(0,1),(F $fontSerif 54 1),[System.Drawing.Brushes]::White,175,103+$y);$g.DrawString($names[$i],(F $fontSans 32 1),[System.Drawing.Brush]::new($dark),300,$y+75);$g.DrawString('? Verified lawyer',(F $fontSans 24),[System.Drawing.Brush]::new($green),300,$y+125);$g.DrawString($special[$i],(F $fontSans 25),[System.Drawing.Brush]::new($muted),300,$y+180);RoundRect $g ([System.Drawing.Brush]::new($green)) 860 ($y+220) 265 72 20;$g.DrawString('View profile',(F $fontSans 23 1),[System.Drawing.Brushes]::White,900,$y+242)}$b.Save("$out\LegalAdvisor-iPhone-lawyers-1284x2778.png",[System.Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$b.Dispose()
Write-Output 'Created 3 screenshots in Downloads.'

