plugins { id 'com.android.application' }

android {
    namespace 'com.losai.legaladvisor'
    compileSdk 36
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'com.losai.legaladvisor'
        minSdk 26
        targetSdk 36
        versionCode project.hasProperty('versionCode') ? project.property('versionCode').toInteger() : 14
        versionName project.hasProperty('versionName') ? project.property('versionName') : '1.2.2'
    }

    signingConfigs {
        release {
            if (System.getenv('CI') == 'true') {
                storeFile file(System.getenv('CM_KEYSTORE_PATH'))
                storePassword System.getenv('CM_KEYSTORE_PASSWORD')
                keyAlias System.getenv('CM_KEY_ALIAS')
                keyPassword System.getenv('CM_KEY_PASSWORD')
            } else {
                def localSigningFile = rootProject.file('keystore.properties')
                if (localSigningFile.exists()) {
                    def localSigning = new Properties()
                    localSigningFile.withInputStream { localSigning.load(it) }
                    storeFile file(localSigning['storeFile'])
                    storePassword localSigning['storePassword']
                    keyAlias localSigning['keyAlias']
                    keyPassword localSigning['keyPassword']
                }
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
